### PR TITLE
Newsweek Clone Template

### PR DESCRIPTION
**Pull request by Mupa1**
This pull request adds a template page for Newsweek Clone. The design is responsive to different screen size and it's created using HTML, CSS, and Bootstrap.

[Live Demo Link](https://cocky-borg-5ade74.netlify.com/)

### CODE REVIEW

**Comment by christianotieno** [comment]
## Pull Request under review by Christian Otieno (TSE)

**Review by christianotieno — CHANGES_REQUESTED** [review]
# **CHANGES REQUIRED** :warning:
Hey @Mupa1 :wave:
-
You have done a good with this job! :tada: Keep it up.
We, however, do have some few changes to carry out before we proceed (see review comment).
##
- Your page is responding very well. Allow me to laud the good use of the bootstrap classes in your project.
- One thing though the content is not centred as it should be.
- This is currently what we have; 👇 
newsweek_clone
- This is what we should be aiming at: 👇 
newsweek
Contents are nicely centred. To achieve we can make use of the `container` class in place of the container-fluid class at least once in the main tag that houses the entire project. 
- Please make these changes and submit another review request.
- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

**Comment by sumancrest0001** [comment]
### Congratulation @Mupa1 It looks good to me. :+1: :+1: :clap: :clap: 
mission

Now you can merge the branch to master and move ahead. 
[TIPS] Please try to avoid **! important** as much as you could. It's not a good practice.

**Comment by Mupa1** [comment]
Thank you @christianotieno  and @sumancrest0001  for your feedback :raised_hands: . Noted, I will try to avoid using  !important in my next projects.

**Pull request merged**
